# Site settings
name: Abhijit Annaldas
description: A Software Engineer, Dreamer, Learner, Reader, Writer, Doer. Believes that every person has potential to change the world. I'm trying do my bit.
title: Abhijit Annaldas - Dreamer, Learner, Reader, Writer, Doer
twitter_username: avannaldas
github_username: avannaldas
keywords: Abhijit, Annaldas, Abhijit Annaldas, Learner, Author, Doer, Health, Fitness, Health and Fitness, Productivity, Personal Finance, Finance, Performance, Habits, Behavior

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8

permalink: /:title.html
future: false

kramdown:
  parse_block_html: true

gems:
  - jekyll-seo-tag
  
