# Site settings
name: Abhijit Annaldas
description: Dreamer, Learner, Reader, Writer, Doer
title: Abhijit Annaldas - Dreamer, Learner, Reader, Writer, Doer
twitter_username: avannaldas
github_username: avannaldas

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8

permalink: /:title.html
future: false

kramdown:
  parse_block_html: true

gems:
  - jekyll-seo-tag
  
